cc_test(
    name = "channel",
    srcs = ["channel.cpp"],
    copts = ["-Iexternal/googletest/googletest/include"],
    deps = [
      "@gtest//:gtest",
      "@gtest//:gtest_main",
      "//channel:channel",
    ],
)
