cc_test(
    name = "channel",
    srcs = ["channel.cpp"],
    copts = ["-Iexternal/googletest/googletest/include"],
    deps = [
      "@googletest//:gtest",
      "@googletest//:gtest_main",
      "//channel:channel",
    ],
)

cc_test(
    name = "channelmeasures",
    srcs = ["channelmeasures.cpp"],
    copts = ["-Iexternal/googletest/googletest/include"],
    deps = [
      "@googletest//:gtest",
      "@googletest//:gtest_main",
      "//channel:channel",
    ],
)

cc_test(
    name = "distribution",
    srcs = ["distribution.cpp"],
    copts = ["-Iexternal/googletest/googletest/include"],
    deps = [
      "@googletest//:gtest",
      "@googletest//:gtest_main",
      "//base:distribution",
    ],
)
